version: '2'
services:
  mantisbt:
    image: prehley/mantisbt:latest
    ports:
    - 8081:80/tcp
    links:
    - mysql:mysql
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      MYSQL_PASSWORD: dbadminPassword
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: dbadmin
    restart: unless-stopped
    volumes:
    - /sqldump:/docker-entrypoint-initdb.d
    command:
    - --default_authentication_plugin=mysql_native_password
